# Logging: SLF4J (via Lombok)
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.de.caritas.cob.messageservice.scheduler=DEBUG

# Keycloak
keycloak.auth-server-url=
keycloak.realm=
keycloak.bearer-only=true
keycloak.resource=agency-service
keycloak.principal-attribute=
keycloak.cors=false
keycloakService.techuser.id=
keycloakService.admin.username=
keycloakService.admin.password=
keycloakService.admin.clientId=admin-cli

# Rocket.Chat
rocket.systemuser.username=system-rc
rocket.systemuser.password=h!Nd958YCDs69fj&f6#b
rocket.credentialscheduler.cron=0 0/5 * * * ?
    onlineberatung.sentry.dsn=https://15943c1dbc1734cb87b2501bfb026af2@o4508975517925376.ingest.de.sentry.io/4509049283739728
sentry.environment=local
sentry.sample-rate=0.25

spring.datasource.url=jdbc:mariadb://localhost:3306/messageservice
spring.datasource.username=messageservice
spring.datasource.password=U*Yz8*8$At6as4qtp5f9

spring.liquibase.user=liquibase
spring.liquibase.password=ZWE&kpcWyWxf7$99vUBR
spring.liquibase.default-schema=messageservice